---
# Enter Your Variables for your workspace
vagrant_hostname: Sora
public_ssh_key: https://github.com/wieczoreko.keys
config_repo_url: git@github.com:wieczoreko/vagrant-ansible.git
vagrant_home: /home/vagrant

vagrant_packages:
- curl
- wget
- vim
- htop
- git
- mc
- rsync
- zsh
- awscli
pathogen_plugins:
  - repo: "https://github.com/ajh17/VimCompletesMe.git"
  - repo: "https://github.com/pearofducks/ansible-vim.git"
  - repo: "https://github.com/scrooloose/nerdtree.git"
  - repo: "git://github.com/jiangmiao/auto-pairs.git"
